language: java
jdk:
  - oraclejdk8
  
sudo: true

addons:
  code_climate:
    repo_token: 2ffed13086231cc79d1c1d1e8a7cf19c1c67c0a5e1cabc66f50c2bc61287f17d

notifications:
  slack:
    rooms:
      - p632:20oR0X45QVtC9RACNHghchWR
    on_success: change
    on_failure: always

after_success:
   - yarn global add codeclimate-test-reporter
   - codeclimate-test-reporter < src/main/app/coverage/lcov.info
